### ISSUE TITLE
Crash on 1.18.2 when loading new world

### ISSUE THREAD

**Issue by mpab1410** [vlad2305m/Sound-Physics-Fabric#64]
```
[15:36:42] [Sound engine/ERROR]: Uncaught exception in thread "Sound engine"
java.lang.NoSuchMethodError: 'net.minecraft.class_1959 net.minecraft.class_638.method_23753(net.minecraft.class_2338)'
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.2) ~[?:?]
	at com.sonicether.soundphysics.ALstuff.SPEfx.getAbsorptionHF(SPEfx.java:103) ~[soundphysics-0.5.5.jar:?]
	at com.sonicether.soundphysics.ALstuff.SPEfx.setEnvironment(SPEfx.java:75) ~[soundphysics-0.5.5.jar:?]
	at com.sonicether.soundphysics.SoundPhysics.finalizeEnvironment(SoundPhysics.java:474) ~[soundphysics-0.5.5.jar:?]
	at com.sonicether.soundphysics.SoundPhysics.evaluateEnvironment(SoundPhysics.java:394) ~[soundphysics-0.5.5.jar:?]
	at com.sonicether.soundphysics.SoundPhysics.onPlaySoundReverb(SoundPhysics.java:81) ~[soundphysics-0.5.5.jar:?]
	at net.minecraft.client.sound.Source.handler$ccf000$OnPlaySoundInjector(Source:533) ~[?:?]
	at net.minecraft.client.sound.Source.play(Source) ~[?:?]
	at net.minecraft.client.sound.SoundSystem.method_19752(SoundSystem:452) ~[?:?]
	at net.minecraft.client.sound.Channel$SourceManager.method_19737(Channel:34) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:140) ~[?:?]
	at net.minecraft.client.sound.SoundExecutor.waitForStop(SoundExecutor:42) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

https://paste.ee/p/QSU2l - Full startup log from MultiMC

**Comment by Konglomneshued** [comment]
I have the **exact** same issue.
